name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup nuget
      uses: warrenbuckley/Setup-Nuget@v1
    
    - name: Restore packages
      run: nuget restore wtrace.sln
    
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.0
      
#    - name: Prepare
#      run: scripts\Update-AssemblyInfoVersionFiles.ps1
#      shell: powershell
    
    - name: Build Debug using MSBuild
      run: msbuild wtrace.sln -m /p:Configuration=Debug
    
    - name: Build Release using MSBuild
      run: msbuild wtrace.sln -m /p:Configuration=Release
      
    - uses: actions/upload-artifact@v2-preview
      with:
        name: Debug_binaries
        path: bin\Debug\wtrace.exe
     
    - uses: actions/upload-artifact@v2-preview
      with:
        name: Release_binaries
        path: bin\Release\wtrace.exe
